import Foundation
import ArgumentParser
import TSCBasic
import SkipSyntax

struct SnippetCommand: SnippetPhase, StreamingCommand {
    static var configuration = CommandConfiguration(commandName: "snippet", abstract: "Transpile a snippet of Swift to Kotlin", shouldDisplay: false)

    @OptionGroup(title: "Snippet Options")
    var snippetOptions: SnippetPhaseOptions

    @OptionGroup(title: "Output Options")
    var outputOptions: OutputOptions

    @Option(name: [.customLong("codebase")], help: ArgumentHelp("Path to codebase to reference", valueName: "skipcode.json"))
    var codebases: [String] = [] // --module name:path

    @Argument(help: ArgumentHelp("List of files to process"))
    var files: [String]

    struct Output : MessageConvertible {
        let kotlin: String?
        let version: String = skipVersion
        let messages: [Message]?
        let duration: TimeInterval?

        /// The raw description is just the Kotlin, with error messages preceeding it
        var description: String {
            var comments = "// Generated by skip.tools \(version)\n"

            for msg in messages ?? [] {
                comments += msg.description.split(separator: "\n").map({ "//" + $0 }).joined(separator: "\n") + "\n"
            }

            return comments + (kotlin ?? "")
        }
    }

    func performCommand(with continuation: AsyncThrowingStream<OutputMessage, Error>.Continuation) async throws {
        let totalSize = try files.compactMap({ try URL(fileURLWithPath: $0).resourceValues(forKeys: [.fileSizeKey]).fileSize }).reduce(0, +)

        // snippets are hardwired to not exceed the default codebase threshold size
        if let codebaseThresholdSize = Self.codebaseThresholdSize, totalSize > codebaseThresholdSize {
            continuation.yield(OutputMessage(Output(kotlin: nil, messages: [Message(kind: .error, message: "Snippet too large \(byteCount(for: .init(totalSize)))")], duration: 0)))
            continuation.finish()
            return
        }

        let sourceFiles = files.map(Source.FilePath.init(path:))
        try await self.transpile(fs: localFileSystem, sourceFiles: sourceFiles, with: continuation)
    }

    private func transpile(fs: FileSystem, sourceFiles: Array<Source.FilePath>, with continuation: AsyncThrowingStream<OutputMessage, Error>.Continuation) async throws {

        let codebaseInfo = CodebaseInfo()

        for codebasePath in codebases {
            // load each of the specified codebases
            let cbdata = try Data(contentsOf: URL(fileURLWithPath: codebasePath))
            let decoder = JSONDecoder()
            let cbinfo = try decoder.decode(CodebaseInfo.self, from: cbdata)
            codebaseInfo.dependentModules.append(cbinfo)
        }

        let transpiler = Transpiler(packageName: nil, sourceFiles: sourceFiles, codebaseInfo: codebaseInfo, transformers: builtinKotlinTransformers())
        try await transpiler.transpile { transpilation in
            // note that transpilation messages are included as part of the output itself, rather than being logged as a message
            let msgs = transpilation.messages
            let output = Output(kotlin: transpilation.output.content, messages: msgs, duration: transpilation.duration)
            continuation.yield(OutputMessage(output))
        }
        continuation.finish()
    }
}

