name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request_target:
    branches:
      - '*'
  #schedule:
    #- cron: '0 0,12 * * *'

jobs:
  #ci-skiphub:
    #if: github.event_name != 'pull_request'
    #uses: skiptools/skiphub/.github/workflows/ci.yml@main

  ci-linux:
    #runs-on: ubuntu-18.4
    runs-on: ubuntu-20.04
    #runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Dispatch skip ci.yml
        run: gh workflow run -R skiptools/skip 'ci.yml'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Dispatch skiphub ci.yml
        run: gh workflow run -R skiptools/skiphub 'ci.yml'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check kotlinc
        run: which kotlinc

      #- name: Swift Test (Debug)
      #  run: KOTLINC=kotlinc swift test -v --configuration debug --parallel

      - name: Swift Test (Release)
        run: KOTLINC=kotlinc swift test -v --configuration release -Xswiftc -enable-testing --parallel

      #- name: Build SkipRunner (Debug)
      #  run: swift build -v --configuration debug -Xswiftc -enable-testing

      - name: Show skiptool output
        run: find .build/

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@v3
        with: 
          path: .build/x86_64-unknown-linux-gnu/release


