name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request_target:
    branches:
      - '*'
  #schedule:
    #- cron: '0 0,12 * * *'

jobs:
  ci-skiphub:
    if: github.event_name != 'pull_request'
    uses: skiptools/skiphub/.github/workflows/ci.yml@main

  ci-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check kotlinc
        run: which kotlinc

      - name: Swift Test Linux (Debug)
        run: KOTLINC=kotlinc swift test -v --configuration debug --parallel

      - name: Swift Test Linux (Release)
        # disabled for CI speed (release build of dependencies is slow)
        if: false
        run: swift test -v --configuration release -Xswiftc -enable-testing --parallel

