name: Continuous Integration

on:
  push:
    branches:
      - '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"

  pull_request_target:
    branches:
      - '*'
  #schedule:
    #- cron: '0 0,12 * * *'

jobs:
  #ci-skiphub:
    #if: github.event_name != 'pull_request'
    #uses: skiptools/skiphub/.github/workflows/ci.yml@main

  ci-linux:
    #runs-on: ubuntu-18.4
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-22.04
    #runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Dispatch skip ci.yml
        run: gh workflow run -R skiptools/skip 'ci.yml'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Dispatch skiphub ci.yml
        run: gh workflow run -R skiptools/skiphub 'ci.yml'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check kotlinc
        run: which kotlinc

      - name: Swift Test (Debug)
        run: KOTLINC=kotlinc swift test -v -c debug --parallel

      - name: Swift Build (Release)
        if: startsWith(github.ref, 'refs/tags/')
        run: swift build --product SkipRunner -c release -Xswiftc -static-stdlib

      - name: Copy skiptool
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p .build/dist/skiptool/x86_64-unknown-linux-gnu/
          cp -a .build/x86_64-unknown-linux-gnu/release/SkipRunner .build/dist/skiptool/x86_64-unknown-linux-gnu/skipstone

      - name: "Upload Build Artifacts"
        # disabled since it uses storage credit
        # TODO: hand off to macBuild, which will public the linux plugin
        # alongside the macOS one (once swift supports plugins on Linux)
        #if: startsWith(github.ref, 'refs/tags/')
        if: false
        uses: actions/upload-artifact@v3
        with: 
          path: .build/dist

